In [60]:
import json,random
import pandas as pd
import spacy
import nltk
import dataframe_image as dfi
nlp = spacy.load("en_core_web_sm")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
data_set = []
#load yelp reviews.json
for line in open('yelp_academic_dataset_review.json', 'rb'):
    data_set.append(json.loads(line))

In [18]:
#list to string method
def list_to_string(list_):
    str1 = "" 
    
    # traverse in the string  
    for ele in list_: 
        str1 += ele + " " 
    
    # return string  
    return str1

In [62]:
#randomly select 5 sentences
sents_5 =[]
while len(sents_5) < 5:
    ran = random.randint(0,len(data_set)-1)
    doc = nlp(data_set[ran]['text'])
    for sent in doc.sents:
        sents_5.append(sent.text)
        if len(sents_5) == 5:
            break
print(sents_5)

['Service was decent, prices fair, food was...', 'Nothing special.', 'Came here for dinner last night with a few girlfriends.', 'I was the one who suggested it based on the Yelp reviews.', 'The food was just very bland.']

In [79]:
#nltk
sents_5_onestring = list_to_string(sents_5)
text = nltk.word_tokenize(sents_5_onestring)
#words=[word.lower() for word in text if word.isalnum()]
result = nltk.pos_tag(text)

result_dict = dict(result)
print(len(result_dict))
df = pd.DataFrame.from_dict(result_dict,orient='index',columns=['NLTK'])
display(df)

35

            NLTK
Service      NNP
was          VBD
decent        JJ
,              ,
prices       NNS
fair         VBP
food          NN
...            :
Nothing      NNP
special       JJ
.              .
Came          NN
here          RB
for           IN
dinner        NN
last          JJ
night         NN
with          IN
a             DT
few           JJ
girlfriends  NNS
I            PRP
the           DT
one           NN
who           WP
suggested    VBD
it           PRP
based        VBN
on            IN
Yelp         NNP
reviews      NNS
The           DT
just          RB
very          RB
bland         RB

In [82]:
#spacy
doc = nlp(sents_5_onestring)
spacy_result={}
token_list=[]
for token in doc:
    #token.text.lower() not in token_list and
        spacy_result[token.text]= token.tag_
df_1 = pd.DataFrame.from_dict(spacy_result,orient='index',columns=['spaCy'])
print(len(spacy_result))
display(df_1)

35

            spaCy
Service        NN
was           VBD
decent         JJ
,               ,
prices        NNS
fair           JJ
food           NN
...             .
Nothing        NN
special        JJ
.               .
Came           VB
here           RB
for            IN
dinner         NN
last           JJ
night          NN
with           IN
a              DT
few            JJ
girlfriends   NNS
I             PRP
the            DT
one            CD
who            WP
suggested     VBD
it            PRP
based         VBN
on             IN
Yelp          NNP
reviews       NNS
The            DT
just           RB
very           RB
bland          JJ

In [83]:
df['spaCy']=pd.Series(spacy_result.values(),index=spacy_result.keys())

display(df)
dfi.export(df,"3.2pos.png")

            NLTK spaCy
Service      NNP    NN
was          VBD   VBD
decent        JJ    JJ
,              ,     ,
prices       NNS   NNS
fair         VBP    JJ
food          NN    NN
...            :     .
Nothing      NNP    NN
special       JJ    JJ
.              .     .
Came          NN    VB
here          RB    RB
for           IN    IN
dinner        NN    NN
last          JJ    JJ
night         NN    NN
with          IN    IN
a             DT    DT
few           JJ    JJ
girlfriends  NNS   NNS
I            PRP   PRP
the           DT    DT
one           NN    CD
who           WP    WP
suggested    VBD   VBD
it           PRP   PRP
based        VBN   VBN
on            IN    IN
Yelp         NNP   NNP
reviews      NNS   NNS
The           DT    DT
just          RB    RB
very          RB    RB
bland         RB    JJ

In [77]:
text1 = nltk.word_tokenize("She's pretty")
print(text1)

['She', "'s", 'pretty']

In [78]:
result1 = nltk.pos_tag(text1)
print(result1)

[('She', 'PRP'), ("'s", 'VBZ'), ('pretty', 'JJ')]